# Generated by Django 4.2.5 on 2023-09-10 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("chess_com_username", models.CharField(max_length=100)),
                ("lichess_username", models.CharField(max_length=100)),
                ("time_class", models.CharField(max_length=20)),
                ("games_num", models.IntegerField()),
                ("analyzed_games", models.IntegerField(default=0, null=True)),
                ("engine_depth", models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name="ChessGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "player_elo",
                    models.IntegerField(help_text="Player's ELO", null=True),
                ),
                (
                    "opponent_elo",
                    models.IntegerField(help_text="Opponent's ELO", null=True),
                ),
                (
                    "opening",
                    models.CharField(
                        help_text="Opening name", max_length=70, null=True
                    ),
                ),
                (
                    "host",
                    models.CharField(
                        help_text="Site name eg. chess.com, lichess",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "short_opening",
                    models.CharField(
                        help_text="Short opening name", max_length=40, null=True
                    ),
                ),
                (
                    "result",
                    models.FloatField(
                        choices=[(1, "white"), (0, "black"), (0.5, "draw")],
                        max_length=10,
                    ),
                ),
                ("date", models.DateTimeField(help_text="Date of the game")),
                (
                    "time_control",
                    models.CharField(
                        help_text="Time control of the game", max_length=20
                    ),
                ),
                (
                    "player_color",
                    models.IntegerField(help_text="Player's color 0-White, 1-Black"),
                ),
                (
                    "mean_player_time_per_move",
                    models.IntegerField(
                        help_text="Mean player time per move", null=True
                    ),
                ),
                (
                    "mean_opponent_time_per_move",
                    models.IntegerField(
                        help_text="Mean opponent time per move", null=True
                    ),
                ),
                ("moves", models.IntegerField(help_text="Number of moves in the game")),
                (
                    "time_class",
                    models.CharField(
                        help_text="eg. rapid, blitz, bullet", max_length=10
                    ),
                ),
                ("phases", models.JSONField(help_text="list with phases of the game")),
                (
                    "mistakes",
                    models.JSONField(
                        help_text="mistakes of the player in phases of the game"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analyze_app.report",
                    ),
                ),
            ],
        ),
    ]
