# Generated by Django 4.1.1 on 2022-09-27 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Raport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("username", models.CharField(max_length=100)),
                ("time_class", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ChessGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "player_elo",
                    models.IntegerField(help_text="Player's ELO", null=True),
                ),
                (
                    "opponent_elo",
                    models.IntegerField(help_text="Opponent's ELO", null=True),
                ),
                (
                    "opening",
                    models.CharField(
                        help_text="Opening name", max_length=100, null=True
                    ),
                ),
                (
                    "result",
                    models.CharField(help_text="Result of the game", max_length=10),
                ),
                ("date", models.DateField(help_text="Date of the game")),
                (
                    "time_control",
                    models.CharField(
                        help_text="Time control of the game", max_length=20
                    ),
                ),
                (
                    "player_color",
                    models.CharField(
                        help_text="Player's color 0-White, 1-Black", max_length=10
                    ),
                ),
                (
                    "mean_player_time_per_move",
                    models.IntegerField(
                        help_text="Mean player time per move", null=True
                    ),
                ),
                (
                    "mean_opponent_time_per_move",
                    models.IntegerField(
                        help_text="Mean opponent time per move", null=True
                    ),
                ),
                ("moves", models.IntegerField(help_text="Number of moves in the game")),
                (
                    "time_class",
                    models.CharField(
                        help_text="eg. rapid, blitz, bullet", max_length=10
                    ),
                ),
                ("phases", models.JSONField(help_text="list with phases of the game")),
                (
                    "mistakes",
                    models.JSONField(
                        help_text="mistakes of the player in phases of the game"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "raport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analyze_app.raport",
                    ),
                ),
            ],
        ),
    ]
