# Generated by Django 4.1.3 on 2022-11-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyze_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chessgame",
            name="short_opening",
            field=models.CharField(
                help_text="Short opening name", max_length=40, null=True
            ),
        ),
        migrations.AlterField(
            model_name="chessgame",
            name="opening",
            field=models.CharField(help_text="Opening name", max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="time_class",
            field=models.CharField(max_length=20),
        ),
    ]
