# Generated by Django 4.2.5 on 2023-09-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyze_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="fail_reason",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
