# Generated by Django 4.1.1 on 2022-09-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyze_app", "0002_raport_games_num"),
    ]

    operations = [
        migrations.AddField(
            model_name="raport",
            name="analyzed_games",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="raport",
            name="games_num",
            field=models.IntegerField(),
        ),
    ]
