# Generated by Django 4.2.5 on 2023-09-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyze_app", "0003_alter_chessgame_player_color_alter_chessgame_result"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chessgame",
            old_name="mistakes",
            new_name="player_mistakes",
        ),
        migrations.AddField(
            model_name="chessgame",
            name="opponent_mistakes",
            field=models.JSONField(
                default={}, help_text="mistakes of the opponent in phases of the game"
            ),
            preserve_default=False,
        ),
    ]
