# Generated by Django 4.1.1 on 2022-09-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyze_app", "0004_alter_chessgame_result"),
    ]

    operations = [
        migrations.RenameField(
            model_name="raport",
            old_name="created_at",
            new_name="created",
        ),
        migrations.RemoveField(
            model_name="raport",
            name="name",
        ),
        migrations.RemoveField(
            model_name="raport",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="raport",
            name="engine_depth",
            field=models.IntegerField(default=10),
        ),
    ]
