# Generated by Django 4.1.1 on 2022-09-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyze_app", "0007_alter_chessgame_player_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chessgame",
            name="player_color",
            field=models.IntegerField(help_text="Player's color 0-White, 1-Black"),
        ),
    ]
