# Generated by Django 4.1.1 on 2022-10-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyze_app", "0008_alter_chessgame_player_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chessgame",
            name="date",
            field=models.DateTimeField(help_text="Date of the game"),
        ),
    ]
