# Generated by Django 4.2.5 on 2023-10-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyze_app", "0003_chessgame_result"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chessgame",
            name="player_color",
            field=models.CharField(
                choices=[("white", "White"), ("black", "Black")],
                help_text="Player color in the game.",
                max_length=10,
            ),
        ),
    ]
