# Generated by Django 4.2.5 on 2023-10-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyze_app", "0003_alter_report_professional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="professional",
            field=models.BooleanField(blank=True),
        ),
    ]
